/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Bluby API
 * Cloudflare Worker backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from '.././mutator/custom-instance';

/**
 * Retrieve operation for /v1/products/
 * @summary Get products
 */
export const getV1Products = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/v1/products/`, method: 'GET', signal });
};

export const getGetV1ProductsQueryKey = () => {
  return [`/v1/products/`] as const;
};

export const getGetV1ProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1Products>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getV1Products>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1ProductsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Products>>> = ({ signal }) =>
    getV1Products(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1Products>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetV1ProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Products>>>;
export type GetV1ProductsQueryError = void;

/**
 * @summary Get products
 */

export function useGetV1Products<
  TData = Awaited<ReturnType<typeof getV1Products>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getV1Products>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetV1ProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create operation for /v1/products/
 * @summary Create products
 */
export const postV1Products = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/v1/products/`, method: 'POST', signal });
};

export const getPostV1ProductsMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1Products>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof postV1Products>>, TError, void, TContext> => {
  const mutationKey = ['postV1Products'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Products>>, void> = () => {
    return postV1Products();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostV1ProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Products>>>;

export type PostV1ProductsMutationError = void;

/**
 * @summary Create products
 */
export const usePostV1Products = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1Products>>, TError, void, TContext>;
}): UseMutationResult<Awaited<ReturnType<typeof postV1Products>>, TError, void, TContext> => {
  const mutationOptions = getPostV1ProductsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Retrieve operation for /v1/products/:productId
 * @summary Get specific product
 */
export const getV1ProductsProductId = (productId: number, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/v1/products/${productId}`, method: 'GET', signal });
};

export const getGetV1ProductsProductIdQueryKey = (productId: number) => {
  return [`/v1/products/${productId}`] as const;
};

export const getGetV1ProductsProductIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1ProductsProductId>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getV1ProductsProductId>>, TError, TData>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1ProductsProductIdQueryKey(productId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ProductsProductId>>> = ({ signal }) =>
    getV1ProductsProductId(productId, signal);

  return { queryKey, queryFn, enabled: !!productId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1ProductsProductId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetV1ProductsProductIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1ProductsProductId>>
>;
export type GetV1ProductsProductIdQueryError = void;

/**
 * @summary Get specific product
 */

export function useGetV1ProductsProductId<
  TData = Awaited<ReturnType<typeof getV1ProductsProductId>>,
  TError = void,
>(
  productId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getV1ProductsProductId>>, TError, TData>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetV1ProductsProductIdQueryOptions(productId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
