/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get user meals
 * @summary Get Meals
 */
export const getMealsV1MealsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meals/`, method: 'GET', signal
    },
      );
    }
  

export const getGetMealsV1MealsGetQueryKey = () => {
    return [`/v1/meals/`] as const;
    }

    
export const getGetMealsV1MealsGetQueryOptions = <TData = Awaited<ReturnType<typeof getMealsV1MealsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealsV1MealsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMealsV1MealsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMealsV1MealsGet>>> = ({ signal }) => getMealsV1MealsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMealsV1MealsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMealsV1MealsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMealsV1MealsGet>>>
export type GetMealsV1MealsGetQueryError = unknown


/**
 * @summary Get Meals
 */

export function useGetMealsV1MealsGet<TData = Awaited<ReturnType<typeof getMealsV1MealsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealsV1MealsGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMealsV1MealsGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new meal
 * @summary Create Meal
 */
export const createMealV1MealsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meals/`, method: 'POST', signal
    },
      );
    }
  


export const getCreateMealV1MealsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealV1MealsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMealV1MealsPost>>, TError,void, TContext> => {
    
const mutationKey = ['createMealV1MealsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMealV1MealsPost>>, void> = () => {
          

          return  createMealV1MealsPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMealV1MealsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMealV1MealsPost>>>
    
    export type CreateMealV1MealsPostMutationError = unknown

    /**
 * @summary Create Meal
 */
export const useCreateMealV1MealsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealV1MealsPost>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof createMealV1MealsPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateMealV1MealsPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get specific meal
 * @summary Get Meal
 */
export const getMealV1MealsMealIdGet = (
    mealId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meals/${mealId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetMealV1MealsMealIdGetQueryKey = (mealId: number,) => {
    return [`/v1/meals/${mealId}`] as const;
    }

    
export const getGetMealV1MealsMealIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>, TError = HTTPValidationError>(mealId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMealV1MealsMealIdGetQueryKey(mealId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>> = ({ signal }) => getMealV1MealsMealIdGet(mealId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(mealId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMealV1MealsMealIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>>
export type GetMealV1MealsMealIdGetQueryError = HTTPValidationError


/**
 * @summary Get Meal
 */

export function useGetMealV1MealsMealIdGet<TData = Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>, TError = HTTPValidationError>(
 mealId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealV1MealsMealIdGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMealV1MealsMealIdGetQueryOptions(mealId,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



