/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get friends list
 * @summary Get Friends
 */
export const getFriendsV1FriendsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/friends/`, method: 'GET', signal
    },
      );
    }
  

export const getGetFriendsV1FriendsGetQueryKey = () => {
    return [`/v1/friends/`] as const;
    }

    
export const getGetFriendsV1FriendsGetQueryOptions = <TData = Awaited<ReturnType<typeof getFriendsV1FriendsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFriendsV1FriendsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFriendsV1FriendsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFriendsV1FriendsGet>>> = ({ signal }) => getFriendsV1FriendsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFriendsV1FriendsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFriendsV1FriendsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFriendsV1FriendsGet>>>
export type GetFriendsV1FriendsGetQueryError = unknown


/**
 * @summary Get Friends
 */

export function useGetFriendsV1FriendsGet<TData = Awaited<ReturnType<typeof getFriendsV1FriendsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFriendsV1FriendsGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetFriendsV1FriendsGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Send friend request
 * @summary Send Friend Request
 */
export const sendFriendRequestV1FriendsRequestUserIdPost = (
    userId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/friends/request/${userId}`, method: 'POST', signal
    },
      );
    }
  


export const getSendFriendRequestV1FriendsRequestUserIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>, TError,{userId: number}, TContext> => {
    
const mutationKey = ['sendFriendRequestV1FriendsRequestUserIdPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  sendFriendRequestV1FriendsRequestUserIdPost(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendFriendRequestV1FriendsRequestUserIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>>
    
    export type SendFriendRequestV1FriendsRequestUserIdPostMutationError = HTTPValidationError

    /**
 * @summary Send Friend Request
 */
export const useSendFriendRequestV1FriendsRequestUserIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>, TError,{userId: number}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof sendFriendRequestV1FriendsRequestUserIdPost>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getSendFriendRequestV1FriendsRequestUserIdPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get pending friend requests
 * @summary Get Friend Requests
 */
export const getFriendRequestsV1FriendsRequestsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/friends/requests`, method: 'GET', signal
    },
      );
    }
  

export const getGetFriendRequestsV1FriendsRequestsGetQueryKey = () => {
    return [`/v1/friends/requests`] as const;
    }

    
export const getGetFriendRequestsV1FriendsRequestsGetQueryOptions = <TData = Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFriendRequestsV1FriendsRequestsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>> = ({ signal }) => getFriendRequestsV1FriendsRequestsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFriendRequestsV1FriendsRequestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>>
export type GetFriendRequestsV1FriendsRequestsGetQueryError = unknown


/**
 * @summary Get Friend Requests
 */

export function useGetFriendRequestsV1FriendsRequestsGet<TData = Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFriendRequestsV1FriendsRequestsGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetFriendRequestsV1FriendsRequestsGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



