/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get recipes
 * @summary Get Recipes
 */
export const getRecipes = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/recipes/`, method: 'GET', signal
    },
      );
    }
  

export const getGetRecipesQueryKey = () => {
    return [`/v1/recipes/`] as const;
    }

    
export const getGetRecipesQueryOptions = <TData = Awaited<ReturnType<typeof getRecipes>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipes>>> = ({ signal }) => getRecipes(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipes>>>
export type GetRecipesQueryError = unknown


/**
 * @summary Get Recipes
 */

export function useGetRecipes<TData = Awaited<ReturnType<typeof getRecipes>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipes>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecipesQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new recipe
 * @summary Create Recipe
 */
export const createRecipe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/recipes/`, method: 'POST', signal
    },
      );
    }
  


export const getCreateRecipeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,void, TContext> => {
    
const mutationKey = ['createRecipe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecipe>>, void> = () => {
          

          return  createRecipe()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipe>>>
    
    export type CreateRecipeMutationError = unknown

    /**
 * @summary Create Recipe
 */
export const useCreateRecipe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRecipe>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof createRecipe>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateRecipeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get specific recipe
 * @summary Get Recipe
 */
export const getRecipe = (
    recipeId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/recipes/${recipeId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetRecipeQueryKey = (recipeId: number,) => {
    return [`/v1/recipes/${recipeId}`] as const;
    }

    
export const getGetRecipeQueryOptions = <TData = Awaited<ReturnType<typeof getRecipe>>, TError = HTTPValidationError>(recipeId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipeQueryKey(recipeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipe>>> = ({ signal }) => getRecipe(recipeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recipeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecipeQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipe>>>
export type GetRecipeQueryError = HTTPValidationError


/**
 * @summary Get Recipe
 */

export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = HTTPValidationError>(
 recipeId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecipeQueryOptions(recipeId,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



