/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get ingredients
 * @summary Get Ingredients
 */
export const getIngredients = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/`, method: 'GET', signal
    },
      );
    }
  

export const getGetIngredientsQueryKey = () => {
    return [`/v1/ingredients/`] as const;
    }

    
export const getGetIngredientsQueryOptions = <TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngredientsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngredients>>> = ({ signal }) => getIngredients(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIngredientsQueryResult = NonNullable<Awaited<ReturnType<typeof getIngredients>>>
export type GetIngredientsQueryError = unknown


/**
 * @summary Get Ingredients
 */

export function useGetIngredients<TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetIngredientsQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create ingredient
 * @summary Create Ingredient
 */
export const createIngredient = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/`, method: 'POST', signal
    },
      );
    }
  


export const getCreateIngredientMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIngredient>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createIngredient>>, TError,void, TContext> => {
    
const mutationKey = ['createIngredient'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIngredient>>, void> = () => {
          

          return  createIngredient()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIngredientMutationResult = NonNullable<Awaited<ReturnType<typeof createIngredient>>>
    
    export type CreateIngredientMutationError = unknown

    /**
 * @summary Create Ingredient
 */
export const useCreateIngredient = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIngredient>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof createIngredient>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateIngredientMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get specific ingredient
 * @summary Get Ingredient
 */
export const getIngredient = (
    ingredientId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/${ingredientId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetIngredientQueryKey = (ingredientId: number,) => {
    return [`/v1/ingredients/${ingredientId}`] as const;
    }

    
export const getGetIngredientQueryOptions = <TData = Awaited<ReturnType<typeof getIngredient>>, TError = HTTPValidationError>(ingredientId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredient>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngredientQueryKey(ingredientId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngredient>>> = ({ signal }) => getIngredient(ingredientId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ingredientId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngredient>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIngredientQueryResult = NonNullable<Awaited<ReturnType<typeof getIngredient>>>
export type GetIngredientQueryError = HTTPValidationError


/**
 * @summary Get Ingredient
 */

export function useGetIngredient<TData = Awaited<ReturnType<typeof getIngredient>>, TError = HTTPValidationError>(
 ingredientId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredient>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetIngredientQueryOptions(ingredientId,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



