/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get ingredients
 * @summary Get Ingredients
 */
export const getIngredientsV1IngredientsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/`, method: 'GET', signal
    },
      );
    }
  

export const getGetIngredientsV1IngredientsGetQueryKey = () => {
    return [`/v1/ingredients/`] as const;
    }

    
export const getGetIngredientsV1IngredientsGetQueryOptions = <TData = Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngredientsV1IngredientsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>> = ({ signal }) => getIngredientsV1IngredientsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIngredientsV1IngredientsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>>
export type GetIngredientsV1IngredientsGetQueryError = unknown


/**
 * @summary Get Ingredients
 */

export function useGetIngredientsV1IngredientsGet<TData = Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredientsV1IngredientsGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetIngredientsV1IngredientsGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create ingredient
 * @summary Create Ingredient
 */
export const createIngredientV1IngredientsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/`, method: 'POST', signal
    },
      );
    }
  


export const getCreateIngredientV1IngredientsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>, TError,void, TContext> => {
    
const mutationKey = ['createIngredientV1IngredientsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>, void> = () => {
          

          return  createIngredientV1IngredientsPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIngredientV1IngredientsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>>
    
    export type CreateIngredientV1IngredientsPostMutationError = unknown

    /**
 * @summary Create Ingredient
 */
export const useCreateIngredientV1IngredientsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof createIngredientV1IngredientsPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateIngredientV1IngredientsPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get specific ingredient
 * @summary Get Ingredient
 */
export const getIngredientV1IngredientsIngredientIdGet = (
    ingredientId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/ingredients/${ingredientId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetIngredientV1IngredientsIngredientIdGetQueryKey = (ingredientId: number,) => {
    return [`/v1/ingredients/${ingredientId}`] as const;
    }

    
export const getGetIngredientV1IngredientsIngredientIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>, TError = HTTPValidationError>(ingredientId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngredientV1IngredientsIngredientIdGetQueryKey(ingredientId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>> = ({ signal }) => getIngredientV1IngredientsIngredientIdGet(ingredientId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ingredientId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetIngredientV1IngredientsIngredientIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>>
export type GetIngredientV1IngredientsIngredientIdGetQueryError = HTTPValidationError


/**
 * @summary Get Ingredient
 */

export function useGetIngredientV1IngredientsIngredientIdGet<TData = Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>, TError = HTTPValidationError>(
 ingredientId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getIngredientV1IngredientsIngredientIdGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetIngredientV1IngredientsIngredientIdGetQueryOptions(ingredientId,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



