/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get meal plans
 * @summary Get Meal Plans
 */
export const getMealPlansV1MealPlansGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meal_plans/`, method: 'GET', signal
    },
      );
    }
  

export const getGetMealPlansV1MealPlansGetQueryKey = () => {
    return [`/v1/meal_plans/`] as const;
    }

    
export const getGetMealPlansV1MealPlansGetQueryOptions = <TData = Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMealPlansV1MealPlansGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>> = ({ signal }) => getMealPlansV1MealPlansGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMealPlansV1MealPlansGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>>
export type GetMealPlansV1MealPlansGetQueryError = unknown


/**
 * @summary Get Meal Plans
 */

export function useGetMealPlansV1MealPlansGet<TData = Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlansV1MealPlansGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMealPlansV1MealPlansGetQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new meal plan
 * @summary Create Meal Plan
 */
export const createMealPlanV1MealPlansPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meal_plans/`, method: 'POST', signal
    },
      );
    }
  


export const getCreateMealPlanV1MealPlansPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>, TError,void, TContext> => {
    
const mutationKey = ['createMealPlanV1MealPlansPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>, void> = () => {
          

          return  createMealPlanV1MealPlansPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMealPlanV1MealPlansPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>>
    
    export type CreateMealPlanV1MealPlansPostMutationError = unknown

    /**
 * @summary Create Meal Plan
 */
export const useCreateMealPlanV1MealPlansPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof createMealPlanV1MealPlansPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateMealPlanV1MealPlansPostMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get specific meal plan
 * @summary Get Meal Plan
 */
export const getMealPlanV1MealPlansPlanIdGet = (
    planId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/meal_plans/${planId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetMealPlanV1MealPlansPlanIdGetQueryKey = (planId: number,) => {
    return [`/v1/meal_plans/${planId}`] as const;
    }

    
export const getGetMealPlanV1MealPlansPlanIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>, TError = HTTPValidationError>(planId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMealPlanV1MealPlansPlanIdGetQueryKey(planId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>> = ({ signal }) => getMealPlanV1MealPlansPlanIdGet(planId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(planId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMealPlanV1MealPlansPlanIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>>
export type GetMealPlanV1MealPlansPlanIdGetQueryError = HTTPValidationError


/**
 * @summary Get Meal Plan
 */

export function useGetMealPlanV1MealPlansPlanIdGet<TData = Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>, TError = HTTPValidationError>(
 planId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlanV1MealPlansPlanIdGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMealPlanV1MealPlansPlanIdGetQueryOptions(planId,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



