import { FoodItem, Meal, PantryItem, Recipe, Group, UserProfile } from '../types';

export const mockFoodItems: Record<string, FoodItem> = {
  eggs: {
    id: '1',
    name: 'Eggs (2 large)',
    calories: 140,
    protein: 12,
    carbs: 2,
    fat: 10,
    processed: 'low',
  },
  avocado: {
    id: '2',
    name: 'Avocado (half)',
    calories: 120,
    protein: 2,
    carbs: 6,
    fat: 10,
    processed: 'low',
  },
  toast: {
    id: '3',
    name: 'Whole Grain Toast (2 slices)',
    calories: 160,
    protein: 6,
    carbs: 30,
    fat: 2,
    processed: 'medium',
  },
  chickenBreast: {
    id: '4',
    name: 'Grilled Chicken Breast (4oz)',
    calories: 180,
    protein: 36,
    carbs: 0,
    fat: 4,
    processed: 'low',
  },
  rice: {
    id: '5',
    name: 'Brown Rice (1 cup cooked)',
    calories: 220,
    protein: 4,
    carbs: 45,
    fat: 2,
    processed: 'low',
  },
  broccoli: {
    id: '6',
    name: 'Steamed Broccoli (1 cup)',
    calories: 55,
    protein: 4,
    carbs: 11,
    fat: 0,
    processed: 'low',
  },
  salmon: {
    id: '7',
    name: 'Baked Salmon (4oz)',
    calories: 200,
    protein: 22,
    carbs: 0,
    fat: 12,
    processed: 'low',
  },
  sweetPotato: {
    id: '8',
    name: 'Roasted Sweet Potato (1 medium)',
    calories: 180,
    protein: 2,
    carbs: 41,
    fat: 0,
    processed: 'low',
  },
  greenBeans: {
    id: '9',
    name: 'Green Beans (1 cup)',
    calories: 40,
    protein: 2,
    carbs: 8,
    fat: 0,
    processed: 'low',
  },
  yogurt: {
    id: '10',
    name: 'Greek Yogurt (1 cup)',
    calories: 120,
    protein: 20,
    carbs: 9,
    fat: 2,
    processed: 'medium',
  },
  berries: {
    id: '11',
    name: 'Mixed Berries (1 cup)',
    calories: 85,
    protein: 1,
    carbs: 20,
    fat: 0,
    processed: 'low',
  },
  energyBar: {
    id: '12',
    name: 'Protein Energy Bar',
    calories: 250,
    protein: 12,
    carbs: 30,
    fat: 8,
    processed: 'high',
  },
};

export const mockMeals: Record<string, Meal> = {
  breakfast: {
    type: 'Breakfast',
    items: [mockFoodItems.eggs, mockFoodItems.avocado, mockFoodItems.toast],
    totalCalories: 420,
    totalProtein: 20,
    totalCarbs: 38,
    totalFat: 22,
  },
  lunch: {
    type: 'Lunch',
    items: [mockFoodItems.chickenBreast, mockFoodItems.rice, mockFoodItems.broccoli],
    totalCalories: 455,
    totalProtein: 44,
    totalCarbs: 56,
    totalFat: 6,
  },
  dinner: {
    type: 'Dinner',
    items: [mockFoodItems.salmon, mockFoodItems.sweetPotato, mockFoodItems.greenBeans],
    totalCalories: 420,
    totalProtein: 26,
    totalCarbs: 49,
    totalFat: 12,
  },
  snacks: {
    type: 'Snacks',
    items: [mockFoodItems.yogurt, mockFoodItems.berries, mockFoodItems.energyBar],
    totalCalories: 455,
    totalProtein: 33,
    totalCarbs: 59,
    totalFat: 10,
  },
};

export const mockPantryItems: PantryItem[] = [
  {
    id: '1',
    name: 'Eggs',
    quantity: 12,
    isScanned: false,
  },
  {
    id: '2',
    name: 'Chicken Breast',
    quantity: 2,
    isScanned: false,
  },
  {
    id: '3',
    name: 'Brown Rice',
    quantity: 1,
    isScanned: false,
  },
  {
    id: '4',
    name: 'Avocados',
    quantity: 3,
    isScanned: false,
  },
  {
    id: '5',
    name: 'Sweet Potatoes',
    quantity: 5,
    isScanned: false,
  },
  {
    id: '6',
    name: 'Greek Yogurt',
    quantity: 1,
    isScanned: true,
    barcode: '1234567890123',
  },
  {
    id: '7',
    name: 'Whole Grain Bread',
    quantity: 1,
    isScanned: true,
    barcode: '9876543210123',
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Avocado Toast with Eggs',
    ingredients: ['Eggs', 'Avocado', 'Whole Grain Bread', 'Salt', 'Pepper'],
    calories: 420,
    protein: 20,
    carbs: 38,
    fat: 22,
    type: 'Basic',
  },
  {
    id: '2',
    name: 'Chicken and Rice Bowl',
    ingredients: ['Chicken Breast', 'Brown Rice', 'Broccoli', 'Olive Oil', 'Garlic', 'Soy Sauce'],
    calories: 455,
    protein: 44,
    carbs: 56,
    fat: 6,
    type: 'DB',
  },
  {
    id: '3',
    name: 'Salmon with Sweet Potato',
    ingredients: ['Salmon', 'Sweet Potato', 'Green Beans', 'Lemon', 'Olive Oil', 'Dill'],
    calories: 420,
    protein: 26,
    carbs: 49,
    fat: 12,
    type: 'AI',
  },
];

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Family',
    members: [
      { id: '1', name: 'You' },
      { id: '2', name: 'Sarah' },
      { id: '3', name: 'Mike' },
      { id: '4', name: 'Emma' },
    ],
  },
  {
    id: '2',
    name: 'Fitness Friends',
    members: [
      { id: '1', name: 'You' },
      { id: '5', name: 'John' },
      { id: '6', name: 'Alex' },
    ],
  },
];

export const mockUserProfile: UserProfile = {
  name: 'Jamie Smith',
  allergies: ['Peanuts', 'Shellfish'],
  dietaryPreferences: ['High Protein', 'Low Processed'],
  intolerances: ['Lactose'],
  goal: 'weight-loss',
}; 