/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileUpdateBio } from './profileUpdateBio';
import type { ProfileUpdateBirthDate } from './profileUpdateBirthDate';
import type { ProfileUpdatePhoneNumber } from './profileUpdatePhoneNumber';

export interface ProfileUpdate {
  bio?: ProfileUpdateBio;
  birth_date?: ProfileUpdateBirthDate;
  private_birth_date?: boolean;
  phone_number?: ProfileUpdatePhoneNumber;
  private?: boolean;
  allow_contact_search?: boolean;
}
