/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Bluby API
 * Cloudflare Worker backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */

export interface ProfileDetails {
  user_id?: number;
  username?: string;
  bio?: string;
  private?: boolean;
  allow_contact_search?: boolean;
}
