/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Bluby API
 * FastAPI backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import type { StatusEnum } from './statusEnum';
import type { ProfileDetails } from './profileDetails';

export interface SuccessResponseProfileDetails {
  status?: StatusEnum;
  body: ProfileDetails;
}
