/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Bluby API
 * Cloudflare Worker backend for the BlubyAI application
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileDetails } from './profileDetails';

export interface SuccessResponseProfileDetails {
  status?: string;
  body?: ProfileDetails;
}
