name = "bluby-backend"
main = "src/index.ts"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "bluby-db"
database_id = "cf600ae4-f3fc-474f-9291-689997832ad4"

[[r2_buckets]]
binding = "bluby_food_images"
bucket_name = "bluby-food-images"
preview_bucket_name = "bluby-food-images-preview"

[[r2_buckets]]
binding = "bluby_user_avatars"
bucket_name = "bluby-user-avatars"
preview_bucket_name = "bluby-user-avatars-preview"

[[kv_namespaces]]
binding = "bluby_user_sessions"
id = "002a1c2caba5491ca4a82d554c8b22dc"

[vars]
ALLOWED_ORIGINS = "https://api.blubyai.com"
# Set ALLOW_ALL_ORIGINS = "true" to enable '*' (not recommended when using cookies)
# ALLOW_ALL_ORIGINS = "false"

[observability.logs]
enabled = true
